// Small frontend controller for the GTI report generator MVP.
// The goal is clarity over cleverness so the flow is easy to follow.

const reportForm = document.getElementById("report-form");
const apiKeyField = document.getElementById("api_key");
const generateButton = document.getElementById("generate-button");
const reportOutput = document.getElementById("report-output");
const rawJsonOutput = document.getElementById("raw-json-output");
const messageBanner = document.getElementById("message-banner");
const statusPill = document.getElementById("status-pill");
const reportTypeField = document.getElementById("report_type");
const companyDtmFields = document.getElementById("company-dtm-fields");
const companyNameField = document.getElementById("company_name");
const primaryDomainField = document.getElementById("primary_domain");
const keywordsField = document.getElementById("keywords");
const monitorIdField = document.getElementById("monitor_id");
const targetField = document.getElementById("target");
const targetLabel = document.getElementById("target-label");
const downloadButton = document.getElementById("download-button");
const scopeFields = document.getElementById("report-scope-fields");
const reportSectionsGroup = document.getElementById("report-sections-group");
const outputFormatGroup = document.getElementById("output-format-group");
const reportActions = document.getElementById("report-actions");
const explorerActions = document.getElementById("explorer-actions");
const explorerButton = document.getElementById("explorer-button");
const companyDtmActions = document.getElementById("company-dtm-actions");
const dtmMonitorsButton = document.getElementById("dtm-monitors-button");
const dtmAlertsButton = document.getElementById("dtm-alerts-button");

const IOC_ENRICHMENT = "IoC Enrichment";
const INDUSTRY_SNAPSHOT_EXPLORER = "Industry Snapshot Explorer";
const COMPANY_EXPOSURE_DTM = "Company Exposure / DTM";

let lastGeneratedReport = "";
let lastDownloadFilename = "";
let lastDownloadFormat = "markdown";

function escapeHtml(text) {
    return text
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#39;");
}

function formatInlineMarkdown(text) {
    // Escape first so any returned content is safe to inject into the page.
    let formattedText = escapeHtml(text);

    formattedText = formattedText.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
    formattedText = formattedText.replace(/`(.+?)`/g, "<code>$1</code>");

    return formattedText;
}

function markdownToHtml(markdown) {
    // This light parser supports the Markdown structures generated by the MVP
    // backend: headings, paragraphs, bold text, inline code, bullet lists,
    // and fenced code blocks.
    const lines = markdown.split(/\r?\n/);
    const htmlParts = [];
    let inList = false;
    let inCodeBlock = false;
    let codeBlockLines = [];

    function closeListIfNeeded() {
        if (inList) {
            htmlParts.push("</ul>");
            inList = false;
        }
    }

    function closeCodeBlockIfNeeded() {
        if (inCodeBlock) {
            htmlParts.push(
                `<pre><code>${escapeHtml(codeBlockLines.join("\n"))}</code></pre>`,
            );
            inCodeBlock = false;
            codeBlockLines = [];
        }
    }

    for (const line of lines) {
        const trimmedLine = line.trim();

        if (trimmedLine.startsWith("```")) {
            closeListIfNeeded();

            if (inCodeBlock) {
                closeCodeBlockIfNeeded();
            } else {
                inCodeBlock = true;
                codeBlockLines = [];
            }

            continue;
        }

        if (inCodeBlock) {
            codeBlockLines.push(line);
            continue;
        }

        if (!trimmedLine) {
            closeListIfNeeded();
            continue;
        }

        if (trimmedLine.startsWith("# ")) {
            closeListIfNeeded();
            htmlParts.push(`<h1>${formatInlineMarkdown(trimmedLine.slice(2))}</h1>`);
            continue;
        }

        if (trimmedLine.startsWith("## ")) {
            closeListIfNeeded();
            htmlParts.push(`<h2>${formatInlineMarkdown(trimmedLine.slice(3))}</h2>`);
            continue;
        }

        if (trimmedLine.startsWith("- ")) {
            if (!inList) {
                htmlParts.push("<ul>");
                inList = true;
            }

            htmlParts.push(`<li>${formatInlineMarkdown(trimmedLine.slice(2))}</li>`);
            continue;
        }

        closeListIfNeeded();
        htmlParts.push(`<p>${formatInlineMarkdown(trimmedLine)}</p>`);
    }

    closeListIfNeeded();
    closeCodeBlockIfNeeded();
    return htmlParts.join("");
}

function showMessage(message, type) {
    messageBanner.hidden = false;
    messageBanner.textContent = message;
    messageBanner.className = `message-banner ${type}`;
}

function clearMessage() {
    messageBanner.hidden = true;
    messageBanner.textContent = "";
    messageBanner.className = "message-banner";
}

function updateStatus(label, stateClass) {
    statusPill.textContent = label;
    statusPill.className = `status-pill ${stateClass}`;
}

function setLoadingState(isLoading) {
    generateButton.disabled = isLoading;
    generateButton.textContent = isLoading ? "Generating..." : "Generate Report";
    updateStatus(isLoading ? "Running" : "Idle", isLoading ? "running" : "idle");
}

function getExplorerButtonLabel() {
    if (reportTypeField.value === INDUSTRY_SNAPSHOT_EXPLORER) {
        return "Explore Industry Snapshots";
    }

    return "Run Explorer";
}

function setExplorerLoadingState(isLoading) {
    explorerButton.disabled = isLoading;
    explorerButton.textContent = isLoading
        ? "Loading..."
        : getExplorerButtonLabel();
    updateStatus(isLoading ? "Running" : "Idle", isLoading ? "running" : "idle");
}

function setCompanyDtmLoadingState(isLoading, action) {
    dtmMonitorsButton.disabled = isLoading;
    dtmAlertsButton.disabled = isLoading;

    if (!isLoading) {
        dtmMonitorsButton.textContent = "Test DTM Monitors";
        dtmAlertsButton.textContent = "Test DTM Alerts";
    } else if (action === "monitors") {
        dtmMonitorsButton.textContent = "Testing Monitors...";
        dtmAlertsButton.textContent = "Test DTM Alerts";
    } else {
        dtmMonitorsButton.textContent = "Test DTM Monitors";
        dtmAlertsButton.textContent = "Testing Alerts...";
    }

    updateStatus(isLoading ? "Running" : "Idle", isLoading ? "running" : "idle");
}

function getSelectedSections() {
    return Array.from(
        document.querySelectorAll('input[name="sections"]:checked'),
        (input) => input.value,
    );
}

function getSelectedOutputFormat() {
    const selectedFormat = document.querySelector('input[name="output_format"]:checked');
    return selectedFormat ? selectedFormat.value : "markdown";
}

function setDownloadState(isReady, filename = "", outputFormat = "markdown") {
    lastDownloadFilename = filename;
    lastDownloadFormat = outputFormat;
    downloadButton.hidden = !isReady;
    downloadButton.disabled = !isReady;
    downloadButton.textContent = outputFormat === "html"
        ? "Download Report (.html)"
        : "Download Report (.md)";
}

function syncTargetRequirement() {
    const isExplorerMode = (
        reportTypeField.value === INDUSTRY_SNAPSHOT_EXPLORER
    );
    const isCompanyExposureDtm = reportTypeField.value === COMPANY_EXPOSURE_DTM;
    const isIocEnrichment = reportTypeField.value === IOC_ENRICHMENT;

    scopeFields.hidden = isExplorerMode || isCompanyExposureDtm;
    reportSectionsGroup.hidden = isExplorerMode || isCompanyExposureDtm;
    outputFormatGroup.hidden = isExplorerMode || isCompanyExposureDtm;
    reportActions.hidden = isExplorerMode || isCompanyExposureDtm;
    explorerActions.hidden = !isExplorerMode;
    companyDtmFields.hidden = !isCompanyExposureDtm;
    companyDtmActions.hidden = !isCompanyExposureDtm;

    targetField.required = isIocEnrichment && !isExplorerMode && !isCompanyExposureDtm;
    targetField.placeholder = isIocEnrichment ? "example.com" : "Company, region, or industry";
    targetLabel.textContent = isIocEnrichment ? "Target Domain" : "Target (Optional)";
    explorerButton.textContent = getExplorerButtonLabel();

    if (isExplorerMode || isCompanyExposureDtm) {
        lastGeneratedReport = "";
        setDownloadState(false);
    }
}

function buildHtmlDownloadDocument(filename, markdown) {
    const documentTitle = escapeHtml(filename.replace(/\.[^.]+$/, ""));
    const renderedReport = markdownToHtml(markdown);

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${documentTitle}</title>
    <style>
        body {
            margin: 0;
            padding: 32px 20px;
            font-family: "Bahnschrift", "Trebuchet MS", "Segoe UI", sans-serif;
            color: #10232d;
            background: linear-gradient(180deg, #edf6f7, #dce9ea);
        }

        main {
            width: min(920px, 100%);
            margin: 0 auto;
            padding: 28px;
            border-radius: 24px;
            background: rgba(255, 255, 255, 0.96);
            box-shadow: 0 22px 48px rgba(17, 45, 56, 0.12);
        }

        h1, h2, h3 {
            font-family: "Franklin Gothic Medium", "Arial Narrow", sans-serif;
        }

        h2 {
            color: #095f63;
            margin-top: 28px;
        }

        p, li {
            line-height: 1.7;
        }

        code {
            font-family: "Consolas", "Courier New", monospace;
            padding: 2px 6px;
            border-radius: 999px;
            background: rgba(13, 127, 122, 0.1);
            color: #095f63;
        }

        pre {
            overflow-x: auto;
            padding: 16px;
            border-radius: 16px;
            background: #10232d;
            color: #f4fffd;
        }

        pre code {
            padding: 0;
            border-radius: 0;
            background: transparent;
            color: inherit;
        }
    </style>
</head>
<body>
    <main>${renderedReport}</main>
</body>
</html>`;
}

function downloadCurrentReport() {
    if (!lastGeneratedReport || !lastDownloadFilename) {
        return;
    }

    const fileContents = lastDownloadFormat === "html"
        ? buildHtmlDownloadDocument(lastDownloadFilename, lastGeneratedReport)
        : lastGeneratedReport;
    const mimeType = lastDownloadFormat === "html"
        ? "text/html;charset=utf-8"
        : "text/markdown;charset=utf-8";
    const downloadUrl = URL.createObjectURL(new Blob([fileContents], { type: mimeType }));
    const downloadLink = document.createElement("a");

    downloadLink.href = downloadUrl;
    downloadLink.download = lastDownloadFilename;
    document.body.append(downloadLink);
    downloadLink.click();
    downloadLink.remove();
    URL.revokeObjectURL(downloadUrl);
}

function formatApiValue(value) {
    if (value === null || value === undefined || value === "") {
        return "<em>not returned by API</em>";
    }

    if (Array.isArray(value)) {
        if (value.length === 0) {
            return "<em>not returned by API</em>";
        }

        return escapeHtml(value.map((item) => (
            typeof item === "object" ? JSON.stringify(item) : String(item)
        )).join(", "));
    }

    if (typeof value === "object") {
        return escapeHtml(JSON.stringify(value));
    }

    return escapeHtml(String(value));
}

function renderRawJsonDetails(rawJson) {
    return `
        <details class="inline-raw-json">
            <summary>Raw JSON</summary>
            <pre>${escapeHtml(JSON.stringify(rawJson, null, 2))}</pre>
        </details>
    `;
}

function renderEndpointResults(endpointResults) {
    if (!Array.isArray(endpointResults) || endpointResults.length === 0) {
        return "<p><strong>Endpoint Checks:</strong> <em>not returned by API</em></p>";
    }

    return `
        <ul>${endpointResults.map((result) => `
            <li>
                <strong>${escapeHtml(String(result.endpoint_name || "endpoint"))}:</strong>
                HTTP ${escapeHtml(String(result.http_status ?? "not returned by API"))}
                | page ${escapeHtml(String(result.page_number ?? "not returned by API"))}
                | params ${formatApiValue(result.request_params)}
                | requested cursor ${formatApiValue(result.requested_cursor)}
                | next link ${formatApiValue(result.next_link_url)}
                | next cursor ${formatApiValue(result.next_cursor)}
            </li>
        `).join("")}</ul>
    `;
}

function renderCompanyDtmContext() {
    return `
        <p><strong>Company Name:</strong> ${formatApiValue(companyNameField.value.trim())}</p>
        <p><strong>Primary Domain:</strong> ${formatApiValue(primaryDomainField.value.trim())}</p>
        <p><strong>Keywords:</strong> ${formatApiValue(keywordsField.value.trim())}</p>
        <p><strong>Monitor ID:</strong> ${formatApiValue(monitorIdField.value.trim())}</p>
    `;
}

function renderIndustrySnapshotResult(responseData) {
    const snapshots = Array.isArray(responseData.snapshots) ? responseData.snapshots : [];
    const snapshotItemsHtml = snapshots.length > 0
        ? `<ul>${snapshots.map((item) => {
            const titleAndName = item.title && item.name && item.title !== item.name
                ? `${escapeHtml(String(item.title))} | ${escapeHtml(String(item.name))}`
                : formatApiValue(item.title || item.name);

            return `<li>
                <strong>Title/Name:</strong> ${titleAndName}<br>
                <strong>Published Date:</strong> ${formatApiValue(item.published_date)}<br>
                <strong>Targeted Industries:</strong> ${formatApiValue(item.targeted_industries)}<br>
                <strong>Targeted Regions:</strong> ${formatApiValue(item.targeted_regions)}<br>
                <strong>Source Regions:</strong> ${formatApiValue(item.source_regions)}<br>
                <strong>Summary/Description:</strong> ${formatApiValue(item.summary_or_description)}<br>
                ${renderRawJsonDetails(item.raw_json)}
            </li>`;
        }).join("")}</ul>`
        : "<p>No object with a title/name containing <code>Industry Snapshot</code> was returned.</p>";

    reportOutput.classList.remove("empty-state");
    reportOutput.innerHTML = `
        <h1>Industry Snapshot Explorer</h1>
        <p><strong>HTTP Status:</strong> ${escapeHtml(String(responseData.http_status))}</p>
        <p><strong>Endpoint Checks:</strong></p>
        ${renderEndpointResults(responseData.endpoint_results)}
        <p><strong>Summary:</strong> ${escapeHtml(String(responseData.snapshot_count || 0))} matching object(s) found.</p>
        <h2>Returned Industry Snapshot Objects</h2>
        ${snapshotItemsHtml}
    `;
}

function renderCompanyDtmMonitorsResult(responseData) {
    const monitors = Array.isArray(responseData.monitors) ? responseData.monitors : [];
    const domainFilter = responseData.domain_filter || "";
    const paginationNote = responseData.truncated
        ? " Retrieval stopped at the safe page limit."
        : "";
    const monitorItemsHtml = monitors.length > 0
        ? `<ul>${monitors.map((item) => `
            <li>
                <strong>Monitor ID:</strong> ${formatApiValue(item.monitor_id)}<br>
                <strong>Monitor Name:</strong> ${formatApiValue(item.monitor_name)}<br>
                <strong>Monitor Type:</strong> ${formatApiValue(item.monitor_type)}<br>
                <strong>Monitor Template:</strong> ${formatApiValue(item.monitor_template)}<br>
                <strong>Created Date:</strong> ${formatApiValue(item.created_date)}<br>
                ${renderRawJsonDetails(item.raw_json)}
            </li>
        `).join("")}</ul>`
        : "<p>No monitor item could be extracted from the current response schema.</p>";

    reportOutput.classList.remove("empty-state");
    reportOutput.innerHTML = `
        <h1>Company Exposure / DTM</h1>
        ${renderCompanyDtmContext()}
        <p><strong>HTTP Status:</strong> ${escapeHtml(String(responseData.http_status))}</p>
        <p><strong>Primary Domain Filter:</strong> ${domainFilter ? `<code>${escapeHtml(String(domainFilter))}</code>` : "<em>none</em>"}</p>
        <p><strong>Requested Page Size:</strong> ${escapeHtml(String(responseData.requested_size || 0))}</p>
        <p><strong>Pagination:</strong> ${escapeHtml(String(responseData.page_count || 0))} page(s) loaded.${escapeHtml(paginationNote)}</p>
        <p><strong>Endpoint Checks:</strong></p>
        ${renderEndpointResults(responseData.endpoint_results)}
        <p><strong>Summary:</strong> ${escapeHtml(String(responseData.monitor_count || 0))} monitor(s) matched out of ${escapeHtml(String(responseData.total_collected || responseData.total_monitor_count || 0))} collected from the API.</p>
        <h2>DTM Monitors Preview</h2>
        ${monitorItemsHtml}
    `;
}

function renderCompanyDtmAlertsResult(responseData) {
    const alerts = Array.isArray(responseData.simplified_preview)
        ? responseData.simplified_preview
        : (Array.isArray(responseData.alerts) ? responseData.alerts : []);
    const paginationNote = responseData.truncated
        ? " Retrieval stopped at the safe page limit."
        : "";
    const alertItemsHtml = alerts.length > 0
        ? `<ul>${alerts.map((item) => `
            <li>
                <strong>Alert ID:</strong> ${formatApiValue(item.id || item.alert_id)}<br>
                <strong>Type:</strong> ${formatApiValue(item.type)}<br>
                <strong>Title/Name:</strong> ${formatApiValue(item.title_or_name)}<br>
                <strong>Severity:</strong> ${formatApiValue(item.severity)}<br>
                <strong>Status:</strong> ${formatApiValue(item.status)}<br>
                <strong>Monitor ID:</strong> ${formatApiValue(item.monitor_id)}<br>
                <strong>Created At:</strong> ${formatApiValue(item.created_at)}<br>
                <strong>Updated At:</strong> ${formatApiValue(item.updated_at)}<br>
                <strong>Alert Type/Category:</strong> ${formatApiValue(item.alert_type_or_category)}<br>
                <strong>Matched Domain/URL/Email/Keyword:</strong> ${formatApiValue(item.matched_indicator)}<br>
                <strong>Raw Attributes Keys:</strong> ${formatApiValue(item.raw_attribute_keys)}<br>
                ${renderRawJsonDetails(item.raw_json)}
            </li>
        `).join("")}</ul>`
        : "<p>No alert item could be extracted from the current response schema.</p>";

    reportOutput.classList.remove("empty-state");
    reportOutput.innerHTML = `
        <h1>Company Exposure / DTM</h1>
        ${renderCompanyDtmContext()}
        <p><strong>HTTP Status:</strong> ${escapeHtml(String(responseData.http_status))}</p>
        <p><strong>Requested Page Size:</strong> ${escapeHtml(String(responseData.requested_size || 0))}</p>
        <p><strong>Monitor ID Filter:</strong> ${responseData.monitor_id ? `<code>${escapeHtml(String(responseData.monitor_id))}</code>` : "<em>none</em>"}</p>
        <p><strong>Pagination:</strong> ${escapeHtml(String(responseData.page_count || 0))} page(s) loaded.${escapeHtml(paginationNote)}</p>
        <p><strong>Endpoint Checks:</strong></p>
        ${renderEndpointResults(responseData.endpoint_results)}
        <p><strong>Summary:</strong> ${escapeHtml(String(responseData.alert_count || 0))} alert(s) normalized out of ${escapeHtml(String(responseData.total_collected || responseData.total_alert_count || 0))} collected from the API.</p>
        <h2>DTM Alerts Preview</h2>
        ${alertItemsHtml}
    `;
}

async function runSelectedExplorer() {
    if (!reportForm.reportValidity()) {
        return;
    }

    clearMessage();
    setExplorerLoadingState(true);
    setDownloadState(false);
    lastGeneratedReport = "";

    try {
        if (reportTypeField.value !== INDUSTRY_SNAPSHOT_EXPLORER) {
            throw new Error("No explorer workflow is selected.");
        }

        const response = await fetch("/explore/industry-snapshots", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                api_key: apiKeyField.value.trim(),
            }),
        });

        const responseData = await response.json();

        if (!response.ok) {
            const errorMessage = responseData.detail || "The backend returned an error.";
            throw new Error(errorMessage);
        }

        renderIndustrySnapshotResult(responseData);
        rawJsonOutput.textContent = JSON.stringify(responseData.raw_json, null, 2);

        if (responseData.http_status === 200) {
            updateStatus("HTTP 200", "success");
            showMessage(
                `Industry Snapshot exploration completed. ${responseData.snapshot_count} matching object(s) found.`,
                "success",
            );
        } else {
            updateStatus(`HTTP ${responseData.http_status}`, "error");
            showMessage(
                `The endpoint responded with HTTP ${responseData.http_status}. Review the raw JSON below.`,
                "error",
            );
        }
    } catch (error) {
        reportOutput.classList.add("empty-state");
        reportOutput.innerHTML = `
            <h3>Explorer request failed</h3>
            <p>${escapeHtml(error.message || "Unknown error.")}</p>
        `;
        rawJsonOutput.textContent = "No valid JSON payload was returned.";
        updateStatus("Error", "error");
        showMessage(error.message || "Explorer request failed.", "error");
    } finally {
        setExplorerLoadingState(false);

        if (!statusPill.classList.contains("success") && !statusPill.classList.contains("error")) {
            updateStatus("Idle", "idle");
        }
    }
}

function buildCompanyDtmPayload() {
    return {
        api_key: apiKeyField.value.trim(),
        company_name: companyNameField.value.trim() || null,
        primary_domain: primaryDomainField.value.trim() || null,
        keywords: keywordsField.value.trim() || null,
        monitor_id: monitorIdField.value.trim() || null,
    };
}

async function testDtmMonitors() {
    if (!reportForm.reportValidity()) {
        return;
    }

    clearMessage();
    setCompanyDtmLoadingState(true, "monitors");
    setDownloadState(false);
    lastGeneratedReport = "";

    try {
        const response = await fetch("/explore/dtm-monitors", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(buildCompanyDtmPayload()),
        });

        const responseData = await response.json();
        if (!response.ok) {
            const errorMessage = responseData.detail || "The backend returned an error.";
            throw new Error(errorMessage);
        }

        renderCompanyDtmMonitorsResult(responseData);
        rawJsonOutput.textContent = JSON.stringify(
            responseData.raw_data || responseData.raw_json,
            null,
            2,
        );

        if (responseData.http_status === 200) {
            updateStatus("HTTP 200", "success");
            showMessage(
                `DTM monitors test completed. ${responseData.monitor_count} monitor(s) matched out of ${responseData.total_collected || responseData.total_monitor_count} collected across ${responseData.page_count} page(s).`,
                "success",
            );
        } else {
            updateStatus(`HTTP ${responseData.http_status}`, "error");
            showMessage(
                `The endpoint responded with HTTP ${responseData.http_status}. Review the raw JSON below.`,
                "error",
            );
        }
    } catch (error) {
        reportOutput.classList.add("empty-state");
        reportOutput.innerHTML = `
            <h3>DTM monitors test failed</h3>
            <p>${escapeHtml(error.message || "Unknown error.")}</p>
        `;
        rawJsonOutput.textContent = "No valid JSON payload was returned.";
        updateStatus("Error", "error");
        showMessage(error.message || "DTM monitors test failed.", "error");
    } finally {
        setCompanyDtmLoadingState(false, "monitors");

        if (!statusPill.classList.contains("success") && !statusPill.classList.contains("error")) {
            updateStatus("Idle", "idle");
        }
    }
}

async function testDtmAlerts() {
    if (!reportForm.reportValidity()) {
        return;
    }

    clearMessage();
    setCompanyDtmLoadingState(true, "alerts");
    setDownloadState(false);
    lastGeneratedReport = "";

    try {
        const response = await fetch("/explore/dtm-alerts", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(buildCompanyDtmPayload()),
        });

        const responseData = await response.json();
        if (!response.ok) {
            const errorMessage = responseData.detail || "The backend returned an error.";
            throw new Error(errorMessage);
        }

        renderCompanyDtmAlertsResult(responseData);
        rawJsonOutput.textContent = JSON.stringify(responseData.raw_json, null, 2);

        if (responseData.http_status === 200) {
            updateStatus("HTTP 200", "success");
            showMessage(
                `DTM alerts test completed. ${responseData.alert_count} alert(s) normalized out of ${responseData.total_collected || responseData.total_alert_count} collected across ${responseData.page_count} page(s).`,
                "success",
            );
        } else {
            updateStatus(`HTTP ${responseData.http_status}`, "error");
            showMessage(
                `The endpoint responded with HTTP ${responseData.http_status}. Review the raw JSON below.`,
                "error",
            );
        }
    } catch (error) {
        reportOutput.classList.add("empty-state");
        reportOutput.innerHTML = `
            <h3>DTM alerts test failed</h3>
            <p>${escapeHtml(error.message || "Unknown error.")}</p>
        `;
        rawJsonOutput.textContent = "No valid JSON payload was returned.";
        updateStatus("Error", "error");
        showMessage(error.message || "DTM alerts test failed.", "error");
    } finally {
        setCompanyDtmLoadingState(false, "alerts");

        if (!statusPill.classList.contains("success") && !statusPill.classList.contains("error")) {
            updateStatus("Idle", "idle");
        }
    }
}

async function generateReport(event) {
    event.preventDefault();

    if (
        reportTypeField.value === INDUSTRY_SNAPSHOT_EXPLORER
    ) {
        await runSelectedExplorer();
        return;
    }

    if (reportTypeField.value === COMPANY_EXPOSURE_DTM) {
        await testDtmMonitors();
        return;
    }

    if (!reportForm.reportValidity()) {
        return;
    }

    const selectedSections = getSelectedSections();
    if (selectedSections.length === 0) {
        reportOutput.classList.add("empty-state");
        reportOutput.innerHTML = `
            <h3>No report generated yet</h3>
            <p>Select at least one report section before generating.</p>
        `;
        rawJsonOutput.textContent = "No response yet.";
        updateStatus("Error", "error");
        showMessage("Select at least one report section.", "error");
        setDownloadState(false);
        return;
    }

    clearMessage();
    setLoadingState(true);
    setDownloadState(false);

    const formData = new FormData(reportForm);
    const payload = {
        api_key: String(formData.get("api_key") || "").trim(),
        report_type: String(formData.get("report_type") || "").trim(),
        year: Number(formData.get("year")),
        target: String(formData.get("target") || "").trim() || null,
        sections: selectedSections,
        output_format: getSelectedOutputFormat(),
    };

    try {
        const response = await fetch("/generate-report", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(payload),
        });

        const responseData = await response.json();

        if (!response.ok) {
            const errorMessage = responseData.detail || "The backend returned an error.";
            throw new Error(errorMessage);
        }

        reportOutput.classList.remove("empty-state");
        reportOutput.innerHTML = markdownToHtml(responseData.report_markdown);
        rawJsonOutput.textContent = JSON.stringify(responseData.raw_data, null, 2);
        updateStatus(responseData.status || "Success", "success");
        lastGeneratedReport = responseData.report_markdown;
        setDownloadState(
            true,
            responseData.downloadable_filename || "gti-report.md",
            payload.output_format,
        );
        showMessage("Report generated successfully.", "success");
    } catch (error) {
        reportOutput.classList.add("empty-state");
        reportOutput.innerHTML = `
            <h3>Report generation failed</h3>
            <p>${escapeHtml(error.message || "Unknown error.")}</p>
        `;
        rawJsonOutput.textContent = "No valid JSON payload was returned.";
        updateStatus("Error", "error");
        lastGeneratedReport = "";
        setDownloadState(false);
        showMessage(error.message || "Report generation failed.", "error");
    } finally {
        generateButton.disabled = false;
        generateButton.textContent = "Generate Report";

        if (!statusPill.classList.contains("success") && !statusPill.classList.contains("error")) {
            updateStatus("Idle", "idle");
        }
    }
}

reportTypeField.addEventListener("change", syncTargetRequirement);
downloadButton.addEventListener("click", downloadCurrentReport);
explorerButton.addEventListener("click", runSelectedExplorer);
dtmMonitorsButton.addEventListener("click", testDtmMonitors);
dtmAlertsButton.addEventListener("click", testDtmAlerts);
reportForm.addEventListener("submit", generateReport);
setDownloadState(false);
syncTargetRequirement();
